### ISSUE TITLE
Extend this overlay to other games

### ISSUE THREAD

**Issue by luca2125** [TheUltimateKerbonaut/SaintsRowOverlay#1]
Hi,

Do you known if is possible change the output to "xinput1_3.dll" ?

Most games not work with "xinput9_1_0.dll"

Thanks !

**Comment by lukawarren** [comment]
Hi,

I don't believe you'd have to make any changes to the code to get that to work - just try renaming the output dll (or for a more permanent solution edit the .vcxproj)

Have fun :)

**Comment by luca2125** [comment]
Thank you I have already done and work !!
